apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextjs-docker-test-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: nextjs-docker-test-secrets

  data:
  - secretKey: DATABASE_URL
    remoteRef:
      key: nextjs-docker-test-prisma-db-url
      property: DATABASE_URL
